name: IGFCD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch :
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: env
    - run : set-env name=Default
    - name : debugging
    - run: echo  ${{ secrets.DOCKER_USERNAME }}
